### ISSUE TITLE
(help): confused..

### ISSUE THREAD

**Issue by ryznxx** [avalynndev/animetize-api#14]
cuz im confusing using this repo so i decided to ask more

**Comment by avalynndev** [comment]
there is no discord link, sorry

**Comment by avalynndev** [comment]
you can either use: https://animetize-docs.vercel.app/ or just ask me il answer. (i might be a little late)

**Comment by ryznxx** [comment]
thats what i need the docs, are you forget to put in readme?

**Comment by avalynndev** [comment]
o, soww abut that. il add it in the readme

**Comment by avalynndev** [comment]
btw when u go to https://animetize-api.vercel.app/ there is a docs link right there..

**Comment by ryznxx** [comment]
yeaah thanks it helps me a lot
